name: 'Docker retag'
description: 'This action is to retag and existing docker image tag from dockerhub or github packages'
author: 'Mostefa Kamal Lala - Cactusoft'
inputs:
  username:
    required: true
    description: 'docker username'
  password:
    required: true
    description: 'docker password'
  repoName:
    required: true
    description: 'The name of repo'
  sourceTag:
    required: true
    description: 'The tag to check for'
  newTags:
    required: true
    description: 'A list of tags to use for retag'
  registry:
      required: true
      description: 'The registry to check, by default is dockerhub'
      default: 'dockerhub'
runs:
  using: 'node12'
  main: 'dist/index.js'
